import { Selector } from 'testcafe';

fixture `New Fixture`
    .page `http://localhost:8081`;

test('New Test', async t => {
    await t
        .typeText(Selector('#username'), 'eversd1')
        .typeText(Selector('#password'), process.env.PASSWORD)
        .click(Selector('#kc-login'))
        .click(Selector('a').withText('Create New Request'))
        .click(Selector('[data-test="requestType"]'))
        .click(Selector('option').withText('Reallocation'))
        .typeText(Selector('[data-test="pcn"]'), '4234')
        .typeText(Selector('[data-test="previousEmployee"]'), 'Dave')
        .typeText(Selector('[data-test="classification"]'), 'acc')
        .click(Selector('#autosuggest__results-item--0').find('div').withText('Account Clerk'))
        .typeText(Selector('[data-test="classOption"]'), 'class')
        .click(Selector('[data-test="appointmentType"]'))
        .click(Selector('option').withText('Permanent').nth(0))
        .click(Selector('[data-test="classifiedType"]'))
        .click(Selector('option').withText('Classified'))
        .typeText(Selector('[data-test="workingTitle"]'), 'fff')
        .click(Selector('[data-test="fte"]'))
        .click(Selector('option').withText('Full Time'))
        .click(Selector('[data-test="location"]'))
        .click(Selector('#autosuggest__results-item--1').find('div').withText('Golden Rule Building'))
        .click(Selector('[data-test="travel"]'))
        .click(Selector('option').withText('None'))
        .typeText(Selector('[data-test="hoursPerWeek"]'), '40')
        .pressKey('tab')
        .typeText(Selector('[data-test="workingHours"]'), '5-5')
        .pressKey('tab')
        .click(Selector('[data-test="schedule"]'))
        .click(Selector('option').withText('M-F part time'))

        .typeText(Selector('[data-test="start-date"]'), '2020-02-29')
        .typeText(Selector('[data-test="end-date"]'), '2021-03-01')
        
        .click(Selector('[data-test="division"]'))
        .click(Selector('#autosuggest__results-item--2').find('div').withText('CHECH - Center for Hlth Equity & Community Hlth'))
        .click(Selector('[data-test="department"]'))
        .click(Selector('#autosuggest__results-item--5').find('div').withText('Dept F'))
        .typeText(Selector('[data-test="unit"]'), 'un')

        .typeText(Selector('[data-test="supervisor"]'), 'd')
        .click(Selector('#autosuggest__results-item--0').sibling().find('div').withText('David J Everson'))
        
        .typeText(Selector('#uid-153-text'), 'posting language')
        .pressKey('tab')
        .typeText(Selector('#uid-157-text'), 'add in')
        .pressKey('tab')
        .typeText(Selector('#uid-165-text'), 'comments')
        .click(Selector('button').withText('Attach Document'))
        .click(Selector('#type-input'))
        .click(Selector('option').withText('Organizational Chart'))
        .click(Selector('#file-input'))
        .setFilesToUpload(Selector('#file-input'), ['raw.csv'])
        .wait(1000)
        .click(Selector('#modal-prevent-closing___BV_modal_body_').find('button').withText('Submit'))
        .wait(1000)

        .click(Selector('button').withText('×'))
        .click(Selector('button').withText('Add additional funding string'))
        .typeText(Selector('#__BVID__231'), '100')
        .pressKey('tab')
        .typeText(Selector('#__BVID__233'), '1')
        .pressKey('tab')
        .typeText(Selector('#__BVID__235'), '1')
        .pressKey('tab')
        .typeText(Selector('#__BVID__237'), '1')
        .pressKey('tab')
        .typeText(Selector('#__BVID__239'), '1')
        .pressKey('tab')
        .typeText(Selector('#__BVID__241'), '1')
        .pressKey('tab')
        .typeText(Selector('#__BVID__243'), '1')
        .pressKey('tab')
        .typeText(Selector('#__BVID__245'), '1')
        .pressKey('tab')
        .typeText(Selector('#__BVID__247'), '1')
        .pressKey('tab')
        .typeText(Selector('#__BVID__249'), '1')
        .pressKey('tab')
        .typeText(Selector('#__BVID__251'), '1')
        .click(Selector('button').withText('Add additional funding string'))
        .typeText(Selector('#__BVID__258'), '23')
        .pressKey('tab')
        .typeText(Selector('#__BVID__260'), '1')
        .pressKey('backspace')
        .typeText(Selector('#__BVID__260'), '2')
        .pressKey('tab')
        .typeText(Selector('#__BVID__262'), '2')
        .pressKey('tab')
        .typeText(Selector('#__BVID__264'), '2')
        .pressKey('tab')
        .typeText(Selector('#__BVID__266'), '2')
        .pressKey('tab')
        .typeText(Selector('#__BVID__268'), '2')
        .pressKey('tab')
        .typeText(Selector('#__BVID__270'), '2')
        .pressKey('tab')
        .typeText(Selector('#__BVID__272'), '2')
        .pressKey('tab')
        .typeText(Selector('#__BVID__274'), '2')
        .pressKey('tab')
        .typeText(Selector('#__BVID__276'), '2')
        .pressKey('tab')
        .typeText(Selector('#__BVID__278'), '2')
        .typeText(Selector('#uid-193-employeeSelector'), 'dave')
        .pressKey('backspace')
        .pressKey('backspace')
        .click(Selector('#autosuggest__results-item--0').find('div').withText('Everson, David J - david.everson@state.mn.us'))
        .typeText(Selector('#uid-197-employeeSelector'), 'pug')
        .click(Selector('strong').withText('Pugh, Joseph'))
        .click(Selector('button').withText('Submit'))
        .click(Selector('a').withText('Log out'));
});